spring.application.name=member-service
server.port = 8085
##for docker
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## Hibernate Configuration
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

# PostgreSQL Server connection
spring.datasource.url=jdbc:postgresql://localhost:5432/trucare_members
spring.datasource.username=postgres
spring.datasource.password=Youdontneed@123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect