server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<segment>.*), /api/users/${segment}
        - id: bus-service
          uri: lb://bus-service
          predicates:
            - Path=/buses/**
          filters:
            - RewritePath=/buses/(?<segment>.*), /api/buses/${segment}
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/buses/**
          filters:
            - RewritePath=/bookings/(?<segment>.*), /api/bookings/${segment}
        - id: seat-service
          uri: lb://seat-service
          predicates:
            - Path=/seats/**
          filters:
            - RewritePath=/seats/(?<segment>.*), /api/seats/${segment}
        - id: route-service
          uri: lb://route-service
          predicates:
            - Path=/routes/**
          filters:
            - RewritePath=/routes/(?<segment>.*), /api/routes/${segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
