spring.application.name=claims-processing-service


# MYSQL Server connection
spring.datasource.url=jdbc:mysql://localhost:3306/trucare
spring.datasource.username= root
spring.datasource.password= Youdontneed@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=update;
