spring:
  kafka:
    bootstrap-servers: localhost:9092  # Adjust Kafka server address
    consumer:
      group-id: claims-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/